all:
  hosts:
    node1:
      ansible_host: 100.0.0.2
      ansible_user: vagrant
      become: true
      become_user: root
      ip: 100.0.0.2
      access_ip: 100.0.0.2
    node2:
      ansible_host: 100.0.0.3
      ansible_user: vagrant
      become: true
      become_user: root
      ip: 100.0.0.3
      access_ip: 100.0.0.3
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
